### ISSUE TITLE
El código de prueba es mala copia del de Gabriel Schimidt

### ISSUE THREAD

**Issue by evolentini** [emirm-byte/Trabajos_Practicos_TSSE#7]
El código de producción es una copia casi exacta del presentado por Gabriel Schimidt salvo por la eliminación de las lineas 

https://github.com/jgabrielschmidt/TSSE_TP3/blob/ed1f6e66275c3ca8e1040f7d6dc088baa9b7c046/src/leds.c#L2

https://github.com/jgabrielschmidt/TSSE_TP3/blob/ed1f6e66275c3ca8e1040f7d6dc088baa9b7c046/src/leds.c#L22

lo que explica perfectamente porque tiene una prueba que no funciona y código inútil en el archivo.

**Comment by emirm-byte** [comment]
solve this issue
